"""One-command font swap for the VWF dialogue pipeline.

  python tools/alshark/fontgen.py <ttf> [--px N] [--baseline B] [--space W]
                                        [--threshold T] [--gap G] [--weight W]

Renders the TTF, bakes the fixed-format glyph/width bins the rebuild expects, and
regenerates the wrap width table. After this, just:
    cd noredist/rebuild && python3 build.py --chd     (then reload)
No asm or address edits needed - the on-disc/asm layout is FIXED (see src/include/
alshark.inc): 95 glyphs x 16-byte stride at $CFA0, widths at $D590, marker $D600; the
bank-0x6D render hook copies 12 rows. The only per-font constraint: glyphs must be <=8px
wide and fit the 12-row cell. fontgen warns (via ttf2font) if a glyph is clipped - tune
--px / --baseline / --threshold until nothing clips, eyeballing noredist/assets/font/
vwf_en_preview.png.
"""
import argparse
import os

from alshark import ttf2font, fontbuild

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
INCBIN = os.path.join(ROOT, 'rebuild', 'incbin')              # committed font bins
ASSET = os.path.join(ROOT, 'noredist', 'assets', 'font', 'vwf_en')  # dev render (gitignored)


def main():
    ap = argparse.ArgumentParser(description='Render + bake a VWF dialogue font.')
    ap.add_argument('ttf', help='font file (TTF/OTF)')
    ap.add_argument('--px', type=int, default=11, help='font pixel size (em)')
    ap.add_argument('--baseline', type=int, default=9, help='baseline row in the 12-row cell')
    ap.add_argument('--cw', type=int, default=8, help='max glyph width (fixed format = 8)')
    ap.add_argument('--ch', type=int, default=12, help='cell height (fixed format = 12)')
    ap.add_argument('--threshold', type=int, default=128, help='1-bit cutoff 0-255')
    ap.add_argument('--gap', type=int, default=1, help='inter-glyph advance gap px')
    ap.add_argument('--space', type=int, default=4, help='advance width of space (0x20)')
    ap.add_argument('--weight', type=float, default=None, help='variable-font wght axis')
    a = ap.parse_args()

    # 1. render the TTF -> editable grid PNG + widths.txt + _preview.png
    ttf2font.build(a.ttf, a.px, a.cw, a.ch, a.baseline, a.threshold, a.gap, a.space,
                   ASSET, a.weight)
    # 2. bake the fixed-format bins the disc/asm read
    g = os.path.join(INCBIN, 'vwf_glyphs.bin')
    w = os.path.join(INCBIN, 'vwf_widths.bin')
    fontbuild.build_compact(ASSET + '.png', ASSET + '.widths.txt', g, w)
    # 3. regenerate the wrap width table that dialogcodec imports
    widths = list(open(w, 'rb').read())
    fw = os.path.join(HERE, 'fontwidths.py')
    with open(fw, 'w') as f:
        f.write('"""Generated by fontgen.py - VWF advance widths (px), ASCII 0x20-0x7E."""\n')
        f.write('WIDTHS = [\n')
        for i in range(0, len(widths), 16):
            f.write('    ' + ', '.join('%d' % x for x in widths[i:i + 16]) + ',\n')
        f.write(']\n')
    print('wrote', fw)
    print('preview: noredist/assets/font/vwf_en_preview.png')
    print('next: cd noredist/rebuild && python3 build.py --chd   (then reload)')


if __name__ == '__main__':
    main()
